cors:
  originPatterns: http://localhost:3000,http://localhost:8080
spring:
  data:
    mongodb:
      uri: mongodb://root:example@127.0.0.1:27017/myspace?authSource=admin
spring-doc:
  pathsToMatch: /api/**
  swagger-ui:
    use-root-path: true